### ISSUE TITLE
Security vulnerability in set-getter@0.1.0

### ISSUE THREAD

**Issue by OronNadiv** [doowb/set-getter#2]
set-getter@0.1.0 -> to-object-path@0.3.0 -> kind-of@3.2.2
kind-of@3.2.2 has a security vulnerability.
Any plan to update the dependencies to address this issue? I'll be happy to create a PR if you need help.

Thank you!

**Comment by OronNadiv** [comment]
@doowb since I could not get @jonschlinkert to fix the security issues vulnerabilities in to-object-path@0.3.0, I created formed the repository and published a new package to npm.  You may use the new package if you needed.
Formed repository: https://github.com/OronNadiv/to-object-path
New NPM package: https://www.npmjs.com/package/to-object-path-js

**Comment by doowb** [comment]
The CVE specifies `kind-of >= 6.0.0 and < 6.0.3`. Version `3.2.2` does not fall within this range, which is fine to use. Some additional discussion can be found [here](https://github.com/jonschlinkert/kind-of/issues/33).

Since the update isn't necessary by itself, I'm going to close this issue.
When `to-object-path` is updated and has a version bump that requires updating here, then I'll make sure to do it at that time.
